### ISSUE TITLE
[Feature Request]: Create a Long Sword Item

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#530] opened 2022-10-29 15:50 UTC
### Describe the new Feature as detailed as possible

- Would need 2 hands to hold (would ignore anything in off-hand)
- Permanent Sweeping Edge effect (power of enchantment lvl 2) (applied without adding an enchantment)
- Further reach than normal sword (50 % increased reach)

**Comment by Charismara** [comment] 2022-11-25 23:21
duplicate of #552

**Closed by Charismara** 2022-11-25 23:21 UTC
Labels: planned
