### ISSUE TITLE
[Feature Request]: Create a Short Sword Item

### ISSUE THREAD

**Issue by Nieadni** [ManasMods/reincarnated_mod#531] opened 2022-10-29 15:51 UTC
### Describe the new Feature as detailed as possible

- Could never be enchanted with Sweeping Edge
- Shorter Reach than Normal Sword (33% decreased reach)

**Comment by Charismara** [comment] 2022-11-25 23:21
duplicate of #552

**Closed by Charismara** 2022-11-25 23:21 UTC
Labels: planned
